version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - redis_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # 외부에서 접근 가능하도록 포트를 노출
    environment:
      - REDIS_PASSWORD=mySecurePassword  # Redis에 대한 비밀번호 설정
    command: ["redis-server", "--requirepass", "mySecurePassword"]  # Redis 서버 시작 시 비밀번호 설정
    networks:
      - redis_network

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
