spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000

  data:
    redis:
      host: localhost
      port: 6379
      password: mySecurePassword
  application:
    name: hhplusconcertreservationservice

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 create, update, none 등으로 설정 가능
      dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8 이상일 경우
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your-secret-key-here

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/concert # 로컬 H2 설정을 유지
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create # H2 사용 시, 스키마 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  secret: your-secret-key-here
